version: '3.7'

services:
  dealbot:
    build: .
    command: npm run docker-compose
    volumes:
      - .:/build
      # - /build/node_modules
    environment:
      - NODE_OPTIONS=--enable-source-maps --trace-warnings
    ports:
      - '3000:1234'
